version: '3.9'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    healthcheck:
      test: [ "CMD-SHELL", "mongo --eval 'db.runCommand({ping:1})'" ] # ping the mongo service
      interval: 10s # check every 10 seconds
      timeout: 5s # timeout after 5 seconds
      retries: 3 # retry 3 times
  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
#  chat:
#    container_name: travelin-chat
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#      - "5005:5005"
#    depends_on:
#      - mongodb